version: 2
jobs:
  flutter_test:
    docker:
      - image: cirrusci/flutter:1.20.3

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Run the application tests
          command: flutter test

  flutter_release:
    docker:
      - image: cirrusci/flutter:1.20.3

    steps:
      - checkout

      - run:
          name: Run Flutter doctor
          command: flutter doctor

      - run:
          name: Flutter release apk
          command: flutter build apk --release

  deploy_to_qa:
    docker:
      - image: busybox:latest
    steps:
      - run:
          name: Deploy to QA
          command: echo "Going to deploy to QA"

workflows:
  version: 2
  sample_pipeline:
    jobs:
      - flutter_test:
          filters:
            branches:
              only:
                - master
      - release_approval:
          type: approval
          requires:
            - flutter_test
      - flutter_release:
          requires:
            - release_approval
      - deploy_to_qa:
          requires:
            - flutter_release